runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon
  static_dir: favicon

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /libs
  static_dir: libs

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest